spring:
  application:
    name: QuizApp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/questiondb
    username: postgres
    password: Pr@deep1998

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
